spring.application.name=billbot
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
DB_URL=jdbc:postgresql://localhost:5432/billbot
USER_NAME=postgres
PASSWORD=aeshPP432@
JWT_SECRET=8f3a9c2d7b6e4f1a9c3d7e8b2a1f6c9d4e8b7c1a2f9d3e6b5c8a1d7e2f9b4c6
FRONT_END_CORS=http://localhost:5173
EMAIL_USERNAME=pranabeshpratihatjgm@gmail.com
EMAIL_PASSWORD=bkbd simk llfq vkvl
SENDER_NAME=BillBot
REDIS_HOST=localhost
REDIS_PORT=6379
GOOGLE_CLIENT_ID=818216185265-67vr6r097i79411hi636c6v3dr6qbjm1.apps.googleusercontent.com
RESET_LINK=http://localhost:5173/reset-password/
IS_HTTPS=false
